Fix unescaped square brackets in percent arrays
samphippen/rubyfmt pull request #226
Opened 2020-08-06 04:44 UTC by robotdana

e.g. `%w{[ ]}` => `%w[\[ \]]` (which is equivalent to `["[", "]"]`)

fixes: #225

This does mean that this is possibly unnecessarily escaped, because
balanced pairs are fine in percent literals BUT this is easier, and
slightly more explicit.

i can't tell anywhere in the ripper data what kind of delimiters were
used. so this is still wrong: `%w{\{}`: before it would be
equivalent to `['{']`,
now it's transformed to `%w[\{]` which is equivalent to `['\\{']`
but that's a preexisting issue, at least we solved the unbalanced [ case
(because %W/I escapes differently than %w/i, this doesn't appear to be
an issue with those)

(also i'm unclear which ruby file i'm supposed to be modifying so i
modified them all)

2020-08-06 08:05 UTC, robotdana commented
(not clear why the build failed, it built fine on my mac)

2020-08-06 10:34 UTC, penelopezone commented
@robotdana this failure is 100% unrelated to your change, I will fix it when I can (I'm recovering from surgery right now!)

2020-08-06 10:43 UTC, robotdana commented
❤️

2020-08-06 11:41 UTC, fables-tales requested changes

2020-08-06 11:41 UTC, penelopezone commented on script/tests/test_array_literals.sh
> +#!/bin/bash
@robotdana you need to add this to https://github.com/penelopezone/rubyfmt/blob/trunk/script/test.sh for it to run in CI. it looks like it's missing right now?

2020-08-30 14:37 UTC, penelopezone commented
manually merged in da5c3631779121f5281726c093f0548e00cf8034

2020-08-30 14:37 UTC, closed without merging